### ISSUE TITLE
Filename based issue when quantizing songs (Windows)

### ISSUE THREAD

**Issue by dobersch** [samim23/polymath#11]
When trying to quantize a song which could before be added without a problem through:
```
python polymath.py -a G3dFpQzu54w
```
there is an error when trying to quantize it to 123 BPM (for testing purposes):
```
python polymath.py -q G3dFpQzu54w -t 123
```
this is the error output:
```
Quantize Audio: Target BPM 123 -- id: G3dFpQzu54w bpm: 136.0 frequency: 133.58 key: C3 timbre: -7.04 name: The Rolling Stones - Jumpin’ Jack Flash (Official Lyric Video) keepOriginalBpm: False
- Quantize Audio: source
Traceback (most recent call last):
  File "C:\polymath\polymath.py", line 674, in <module>
    main()
  File "C:\polymath\polymath.py", line 640, in main
    quantizeAudio(videos[idx], bpm=tempo, keepOriginalBpm = keepOriginalBpm, pitchShiftFirst = pitchShiftFirst)
  File "C:\polymath\polymath.py", line 371, in quantizeAudio
    sf.write(path, strechedaudio, sr)
  File "C:\ProgramData\Miniconda3\envs\polymath\lib\site-packages\soundfile.py", line 430, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "C:\ProgramData\Miniconda3\envs\polymath\lib\site-packages\soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\ProgramData\Miniconda3\envs\polymath\lib\site-packages\soundfile.py", line 1264, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\ProgramData\Miniconda3\envs\polymath\lib\site-packages\soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:\\polymath/processed/G3dFpQzu54w - The Rolling Stones - Jumpin’ Jack Flash (Official Lyric Video) - Key: C3 - Freq: 133.58 - Timbre: -7.04 - BPM Original: 135 - BPM: 123.wav': System error.
```
as far as I understand, the reason is the filename. When inserting in line 368 in polymath.py the following:
```
    path = os.getcwd() + "/processed/testfile.wav"
```
the (first) file gets saved without a problem. This is obviously not a *real* solution to the problem.

So I changed the script and got rid of the ":"s which Windows doesn't seem to like (apart from volume names):
```
    # save audio to disk   
    path = os.getcwd() + "/processed/" + vid.id +  " - " + vid.name + " - Key " + vid.audio_features['key']  + " - Freq " + str(round(vid.audio_features['frequency'],2)) + " - Timbre " + str(round(vid.audio_features['timbre'],2)) + " - BPM Original " + str(int(vid.audio_features['tempo'])) + " - BPM " + str(bpm) +".wav"
    sf.write(path, strechedaudio, sr)
```
and for the stems files:
```
        # save stems to disk
        path = os.getcwd() + "/processed/" + vid.id +  " - " + vid.name + " - Stem " + stem +  " - Key " + vid.audio_features['key']  + " - Freq " + str(round(vid.audio_features['frequency'],2)) + " - Timbre " + str(round(vid.audio_features['timbre'],2)) + " - BPM Original " + str(int(vid.audio_features['tempo'])) + " - BPM " + str(bpm) +".wav"
        sf.write(path, strechedaudio, sr)
```
Maybe it would be wise to escape the filenames in a proper way for the different OSs, but I don't know the conventions and now it's working for me.

I've added the diff-file in case someone has the same problem.
[diff.txt](https://github.com/samim23/polymath/files/10714108/diff.txt)

**Comment by samim23** [comment]
Nice catch. This has been fixed in the most recent commit. Thanks!

**Comment by reneoelke** [comment]
Good stuff! Thanks @dobersch for the patch and @samim23 for applying it.

For the sake of completeness I add the corresponding commit here: https://github.com/samim23/polymath/commit/f200a1eddfccef1810e0b5bb6b6beca221e6ce1a 😉

**Comment by dobersch** [comment]
@samim23 
Thanks for changing the code, tried it out.

Now it works better than before - BUT only one half: the main audio (source) gets quantized and saved but the stem files do *not* get saved and I suspect that it has something to do with filenames.

There's *one* file with a size of 0 Bytes (see attached screenshot).
![2023-02-12 15_02_04-processed](https://user-images.githubusercontent.com/2650978/218315737-494e87aa-16cc-47be-9070-966c3412aa24.png)

After examining the code, this is what i found:

In line 405 there is still a ":" which leads to the same problem we tried to solve in the first place:
```
        path = f"{path_prefix} - Stem: {stem} - {path_suffix}.wav"
```
Hope that helps 🤓

**Comment by samim23** [comment]
Phew, missed one, nice catch! Fixed and commited, thanks!
