### ISSUE TITLE
numpy problem during installation

### ISSUE THREAD

**Issue by Loris-bite** [samim23/polymath#12]
During the installation process i've got a error: `
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
`
i've tried to upgrade pip3 and install an older version of numpy but i got the same error.

**Comment by samim23** [comment]
This was due a required old numpy version in the requirements.txt. It has now been updated and should work it you pull and try again.
