### ISSUE TITLE
syntaxError

### ISSUE THREAD

**Issue by Loris-bite** [samim23/polymath#15]
When i run i've got a syntax error :
`python polymath.py -a /Users/loris/Desktop/Music/polymath2023/`
  
`File "polymath.py", line 60
    command = f"ffmpeg -hide_banner -loglevel panic -i {file} -ab 160k -ac 2 -ar 44100 -vn -y {vidobj.audio}"
                                                                                                            ^
SyntaxError: invalid syntax
`

**Comment by samim23** [comment]
What platform (windows, mac, linux) are you on?

**Comment by Loris-bite** [comment]
mac (Big Sur 11.7.3)

**Comment by samim23** [comment]
Do you have `ffmpeg` installed on your system?

`brew install ffmpeg`

**Comment by Loris-bite** [comment]
I didn't have it, but after installing it I still have the same error.

**Comment by faradox** [comment]
@Loris-bite  What does the output of `python --version` say?

**Comment by Loris-bite** [comment]
Python 2.7.16

**Comment by samim23** [comment]
Polymath requires Python 3.7, 3.8, 3.9 or 3.10 (no bigger than 3.10 on MacOs!). Please try upgrading your setup!

**Comment by Loris-bite** [comment]
I have Python 3.10. If i use `python3 --version` the output say Python 3.10.6

**Comment by faradox** [comment]
Then you should also use python3 to call polymath, i.e.

 `python3 polymath.py -a /Users/loris/Desktop/Music/polymath2023/`

Also make sure that you installed the requirements with the correct pip (likely `pip3`) or consider setting up a [conda](https://conda.io) environment.

**Comment by Loris-bite** [comment]
I Reinstalled using pip3 and now it works!

**Comment by samim23** [comment]
awesome!
