### ISSUE TITLE
OSError: [WinError 87] Paramètre incorrect when i try to add a youtube video

### ISSUE THREAD

**Issue by DomDumont** [samim23/polymath#3]
Hi,
On Windows 10, I got this error when I try to add a youtube video : 

\yt_dlp\utils.py", line 886, in __init__
... AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
OSError: [WinError 87] Paramètre incorrect

**Comment by samim23** [comment]
Not sure why this is happening and don't have a Windows10 system to test it. 

You can try replacing the line from `yt_dlp import YoutubeDL` with `import youtube_dl as YoutubeDL`
and installing `pip install youtube_dl` before hand. It's slower than the lib i used but might work for you. 

Or you could investigate `https://github.com/yt-dlp/yt-dlp` and if you find out what's wrong, give me a hint!

Let me know!
