### ISSUE TITLE
install on M1 mac stopped working

### ISSUE THREAD

**Issue by mgiraldo** [samim23/polymath#37]
macOS Ventura 13.2.1 (22D68)
Apple M1 Max

I pulled the latest (5b89899) commit which comes with os/platform-specific tensorflow and am getting whis error on `pip install`:

```
ERROR: Could not find a version that satisfies the requirement tensorflow<2.10,>=2.4.1 (from basic-pitch) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.10,>=2.4.1
```

I had previously managed to get it working (#22) so not sure what is going on now.

**Comment by ottocoster** [comment]
Same issue here. Mac M1, Python 3.10

**Comment by evilsocket** [comment]
same, macOS 13.1, M1 Max

**Comment by evilsocket** [comment]
I can build and run 431f07a829f03147ff9689343f874dee73dba6bb on the same computer

**Comment by Logic-Beach** [comment]
Can confirm. I did `git checkout 55d9020` to roll back to (my knowledge) the last working commit and it's working fine again.
