### ISSUE TITLE
incomplete installation on ubuntu --> basic-pitch 0.2.0 depends on tensorflow<2.10 and >=2.4.1

### ISSUE THREAD

**Issue by mo-we** [samim23/polymath#38]
Ciao Samim,
I tried installing polymath on my Ubuntu 22.10 machine with Python 3.10.7, and i got the following error:

```
`ERROR: Cannot install basic-pitch==0.2.0 and tensorflow==2.11 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tensorflow==2.11
    basic-pitch 0.2.0 depends on tensorflow<2.10 and >=2.4.1`
```

I tried to loosen the version for tensorflow but then i got tensorflow2.9 and other errors:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 3.19.6 which is incompatible.
clean-fid 0.1.29 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.
`
Any hint is appreciated. Thanks a lot for your great piece of software! (polymath is installing and running fine on my mac OS machine)

**Comment by samim23** [comment]
Thanks for flagging this! Looking into it and will push a fix asap.

**Comment by mgiraldo** [comment]
this is an issue similar to #37

**Comment by samim23** [comment]
This should now be resolve. please check and let me know if there are any other issues. Thanks!

**Comment by mgiraldo** [comment]
i think the latest `tensorflow-metal` [is `0.5.0`](https://developer.apple.com/metal/tensorflow-plugin/) (not `2.9` as requested in the `requirements.txt`):

```py
ERROR: Could not find a version that satisfies the requirement tensorflow-metal==2.9 (from versions: 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1)
ERROR: No matching distribution found for tensorflow-metal==2.9
```

if i change that to `0.5.0` in the requirements i get the same issues with `basic-pitch`:

```py
ERROR: Could not find a version that satisfies the requirement tensorflow<2.10,>=2.4.1 (from basic-pitch) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.10,>=2.4.1
```

for some reason `baci-pitch` keeps looking for tensorflow even though i have `tensorflow-metal` and `tensorflow-macos` installed? the setup.cfg seems to [cover this case](https://github.com/spotify/basic-pitch/blob/main/setup.cfg#L42-L43), though 🤔

**Comment by mgiraldo** [comment]
it's possible that the latest `basic-pitch` is not published in the pip package repo. i pip installed directly from github as [described here](https://github.com/spotify/basic-pitch/issues/60#issuecomment-1436689977) and was able to process files again 👍 

```py
pip install git+https://github.com/spotify/basic-pitch.git
```

**Comment by mo-we** [comment]
thanks! with @mgiraldo separate installation of `basic-pitch` it is working now. So great! :heart:

**Comment by samim23** [comment]
Love it! Will add the the trick @mgiraldo into the readme. Thank you all and happy polymathing! and please do join the discord community, you find the link in the readme :)
