### ISSUE TITLE
Cannot access repository

### ISSUE THREAD

**Issue by nathangur** [samim23/polymath#5]
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I haven't had this issue with gitub before, and I'm guessing it might be something on your end? Cheers!

**Comment by ramyareye** [comment]
try `git clone https://github.com/samim23/polymath`

**Comment by samim23** [comment]
The readme has been updated to include this fix for clarity. Thanks!
