### ISSUE TITLE
segmentation fault when extracting midi on n6DAqMFe97E windows wsl2

### ISSUE THREAD

**Issue by alexisheloir** [samim23/polymath#55]
I have performed a Fresh install of wsl2 on my laptop,
then installed tensorflow, cuda and polymath following the instructions at https://github.com/samim23/polymath and https://www.tensorflow.org/install/pip
GPU support is enabled

when trying 
python polymath.py -a n6DAqMFe97E -q all -t 120 -m
steps 1 to 7 seem to succeed

step 6 gives the following warning : 

`UserWarning: power_to_db was called on complex input so phase information will be discarded. To suppress this warning, call power_to_db(np.abs(D)**2) instead.`

step 8 gives the following warnings : 

```
ffprobe: /home/alexis/anaconda3/envs/tf/lib/libncursesw.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)
ffprobe: /home/alexis/anaconda3/envs/tf/lib/libncursesw.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)
ffprobe: /home/alexis/anaconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)
ffmpeg: /home/alexis/anaconda3/envs/tf/lib/libncursesw.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)
ffmpeg: /home/alexis/anaconda3/envs/tf/lib/libncursesw.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)
ffmpeg: /home/alexis/anaconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libcaca.so.0)
```
then displays the following message :

```
- Extract Midi
Segmentation fault
```

**Comment by samim23** [comment]
it strikes me its related to your conda environment setup. Have you tried installing the library that your warnings talk about? conda install -c rios libcaca
