### ISSUE TITLE
Fatal Error with metadata (pyproject.toml)

### ISSUE THREAD

**Issue by nathangur** [samim23/polymath#6]
I have gone ahead and created a log of what happened in the file below: 
[error.txt](https://github.com/samim23/polymath/files/10694511/error.txt)

**Comment by nathangur** [comment]
This occurs when trying to use this command: `pip install -r requirements.txt`

**Comment by eljeff** [comment]
Not sure if this helps you, but I was only able to install correctly using Python 3.9.
It looks like you are on 3.11...
`setup.py:66: RuntimeWarning: NumPy 1.20.3 may not yet support Python 3.11.` ...from your logs

If you can downgrade, that was the simplest fix for me.
Big caveat - I am on Mac so not sure how much difference that makes.

**Comment by akx** [comment]
Yep, the numpy requirement in the requirements file is way too strict. This would be fixed by https://github.com/samim23/polymath/pull/2/commits/3c1a2a29db93695955968eb0f4c3bb6b8bb4afac in my PR.

**Comment by federico-pepe** [comment]
I have some problems too:

`Traceback (most recent call last):
  File "..../Developer/polymath-main/polymath.py", line 16, in <module>
    import numpy as np 
ModuleNotFoundError: No module named 'numpy'`

But if I run `pip3 install numpy` I already have it installed

`Requirement already satisfied: numpy in /opt/homebrew/lib/python3.10/site-packages (1.23.5)`

**Comment by slurpyb** [comment]
Definitely be using venv/pipenv for now

**Comment by samim23** [comment]
This has been fixed now with an updated requirements.txt
