### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by rafaelmmk** [samim23/polymath#7]
Hello friends, thank you for this library, I found it amazing!

I was impressed with the results on the already separated songs and I'm considering buying a better computer if it makes sense.

I have an old computer running Linux (i5 + 8gb memory) and it's taking years to do work on 4 songs. 

Will it make a difference if I run it on a more powerful one with a GPU?

**Comment by samim23** [comment]
The more powerful your machine, the faster. Having a good GPU makes a big difference in speed.
