### ISSUE TITLE
The stereo sound source will become mono when need to be converted.

### ISSUE THREAD

**Issue by 398noe** [samim23/polymath#9]
Hi, this is noe. Thanks your awesome works.

As the title says, if the input audio requires conversion (e.g., if it has a sampling rate other than 44.1 kHz, or if it is an mp3 instead of a wav), the input audio seems to be converted in a mono format. As a result, the output audio will sound very different.

This problem does not occur with Download type videos from YouTube or 44.1kHz and wav type sound sources.

Have a nice day!

**Comment by 398noe** [comment]
For fix this issue,
We should add "mono=False" and set sr=None(This is separate from the Issue title, but if you do not set sr=None, it will read at 22050 Hz.) of librosa.load
https://librosa.org/doc/main/generated/librosa.load.html

https://github.com/samim23/polymath/blob/245d7769c42bf3f35af463f1e32b9f9a07cb4559/polymath.py#L133
and
https://github.com/samim23/polymath/blob/245d7769c42bf3f35af463f1e32b9f9a07cb4559/polymath.py#L146
to
```
 y, sr = librosa.load(path=vid, mono=False, sr=None) 
```

and when librosa load as stereo, we should be transpose for export with soundfile library.
https://github.com/bastibe/python-soundfile/issues/276

Regarding this, it may be necessary to decide whether or not to transpose them depending on the number of channels.

It works for my environments.
```
        # check if is mp3 and convert it to wav
        if vid.endswith(".mp3"):
            # convert mp3 to wav and save it
            print('converting mp3 to wav:', vid)
            y, sr = librosa.load(path=vid, sr=None, mono=False)
            path = os.getcwd() + "/library/"+audioid+".wav"
            # resample to 44100k if required
            if sr != 44100:
                print('converting audio file to 44100:', vid)
                y = librosa.resample(y, orig_sr=sr, target_sr=44100)
            # we need transpose if loaded sound type is stereo. 
            sf.write(path, y.T, 44100)
            vid = path

        # check if is wav and copy it to local folder
        elif vid.endswith(".wav"):
            path1 = vid
            path2 = os.getcwd() + "/library/"+audioid+".wav"
            y, sr = librosa.load(path=vid, sr=None, mono=False)
            if sr != 44100:
                print('converting audio file to 44100:', vid)
                # we need transpose if loaded sound type is stereo. 
                y = librosa.resample(y, orig_sr=sr, target_sr=44100)
                sf.write(path2, y.T, 44100)
            else:
                shutil.copy2(path1, path2)
            vid = path2
```

**Comment by samim23** [comment]
Nice catch, great suggestions. I've included this in the last commit. Thanks!
